INSERT INTO ROL(ID_ROL,DESCRIPTION) values (NEXTVAL('ID_ROL_SEQ'),'ADMIN')
INSERT INTO SUBSCRIPTION_USER (ID_USER,PASSWORD,USER_NAME) VALUES (NEXTVAL('USER_ROL_SEQ'),'$2a$12$AwO/5M.YJHtkB1oldknPj.07J1lKjXjUTW7KU.Xokqoi4Lo9M7UG6','admin@gmail.com');
INSERT INTO USER_ROL(ID_USER_ROL,ID_ROL,ID_USER) VALUES (NEXTVAL('USER_ROL_SEQ'),CURRVAL('ID_ROL_SEQ'),CURRVAL('ID_ROL_SEQ'));
