mail-config:
  subject: "Subscription has ben successfully"
  message: "message"

resilience4j:
  ratelimiter:
    configs:
      defecto:
        timeoutDuration: 1s
        limitRefreshPeriod: 5s
        limitForPeriod: 100
    instances:
      retrieves-subscriptions-rate-limiter:
        base-config: defecto
