mail-config:
  subject: "Subscription has ben successfully"
  message: "message"

resilience4j:
  ratelimiter:
    configs:
      properties:
        timeoutDuration: 10000
        limitRefreshPeriod: 60000
        limitForPeriod: 2
    instances:
      retrieves-subscriptions-rate-limiter:
        base-config: properties
  bulkhead:
    instances:
      retrieve-subscription-bulkhead:
        maxWaitDuration: 0
        maxConcurrentCalls: 2
  circuitBreaker:
    configs:
      defecto:
        sliding-window-size: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      send-email-circuit-breaker:
        base-config: defecto
  retry:
    instances:
      cancel-subscription:
        maxRetryAttempts: 4
        waitDuration: 10000
        retryExceptions:
          - java.util.concurrent.TimeoutException
